### ISSUE TITLE
I can't use de plugin becouse i can't see it

### ISSUE THREAD

**Issue by nikolaievich** [francodacosta/atom-php-getters-setters#39]
i don't know how to use it if it dont see it in "packages->" menu... sorry, my english is realy poor :)

**Comment by amigabits** [comment]
I have a similar issue. The package is installed and I have used it successfully for a long time, but I noticed just last week the option has disappeared from the Packages menu. There is a discussion about Atom Packages disappearing over on the Atom forum.

https://discuss.atom.io/t/atom-packages-disappear/57020

**Comment by Caitbug** [comment]
I was having this issue as well - Changing line 12 in menus > my-package.cson seems to have fixed it on my end. Narrowed down the issue by creating a context menu with the same attributes, and received error 

> "Uncaught Error: Could not call remote function 'emit'. Check that the function signature is correct. Underlying error: Invalid template for MenuItem: must have at least one of label, role or type" 

upon attempting to open the context menu. Changed to a divider since that seems to have been the intent.
